name: Run tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Use Node.js 16.18.0
        uses: actions/setup-node@v4
        with:
          node-version: '16.18.0'

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.11.0
        with:
          mongodb-version: '7.0'
          mongodb-port: 27018

      - name: Setup redis
        uses: shogo82148/actions-setup-redis@v1
        with:
          redis-version: '7.x'

      - run: npm install

      - run: npm test
        env:
          SECRET: 123
